---
title: "houston_plots"
author: "Ivanna Rodríguez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages(pacman)
pacman::p_load(sf, tidyverse, patchwork, tidycensus, readxl, magrittr, here, arrow)
```

```{r}
folder_15 <- 'E:/acs5_block_2015_data/'
folder_20 <- 'E:/acs5_block_2020_data/'
plots_folder <- 'plots/'

states <- c("TX")
cities <- c("Houston")
```

```{r}
# caution: heavy shapefile takes a few mins to load
folder <- 'E:/shapefiles/'
shp_15_tst <- st_read(paste0(folder, "usa_block_groups_2015.geojson"))
```
```{r}
# tx <- shp_15_tst %>% filter(GEOID %in% )
```


```{r}
get_city_data <- function(var) {
  df_15 <- read_parquet(paste0(folder_15, paste0("dkl_", var, "_15_blkgrp_all_states.parquet"))) %>% ungroup()
  df_20 <- read_parquet(paste0(folder_20, paste0("dkl_", var, "_20_blkgrp_all_states.parquet"))) %>% ungroup()
  
  df_flt_15 <- df_15 %>%
    filter(state_codes %in% states,
           str_detect(cbsa_title, cities)) %>%
    mutate(year = 2015)
  
  df_flt_20 <- df_20 %>%
    filter(state_codes %in% states,
           str_detect(cbsa_title, cities)) %>%
    mutate(year = 2020)
  
  return(rbind(df_flt_15, df_flt_20))
}
  
df_houst_race <- get_city_data("race")
df_houst_income <- get_city_data("income")
df_houst_educ <- get_city_data("educ")
df_houst_empl <- get_city_data("empl")
```

```{r}
plot_bars <- function(df, variable) {
  df %>%
    select(group_label, cbsa_fips, label, dkl_bin, year) %>%
    distinct() %>%
    ggplot(aes(x = label, y = dkl_bin, fill = fct_rev(factor(year)))) +
    coord_flip() +
    geom_bar(stat = "identity", position = "dodge") +
    geom_text(aes(label = round(dkl_bin, digits = 2)), 
              position = position_dodge(width = 0.9), hjust = -0.1, size = 3) +
    scale_fill_viridis_d() +  
    labs(title = paste("DKL by", variable  , "Buckets, Houston Metro Area"),
         fill = "Year") +
    theme_minimal() +
    theme(legend.position = "right",
          axis.title.y = element_blank())
    
}
```

```{r}
plot_bars(df_houst_race, "Race")
ggsave(paste0(plots_folder, "race_bars_houston.png"), width = 10, height = 6, dpi = 300)

plot_bars(df_houst_income, "Income")
ggsave(paste0(plots_folder, "income_bars_houston.png"), width = 10, height = 6, dpi = 300)

plot_bars(df_houst_empl, "Employment Status")
ggsave(paste0(plots_folder, "empl_bars_houston.png"), width = 10, height = 6, dpi = 300)

plot_bars(df_houst_educ, "Educational Attainment")
ggsave(paste0(plots_folder, "educ_bars_houston.png"), width = 10, height = 6, dpi = 300)
```

```{r}
map_dkl <- function(df, variable, year, max_range) {
  fig <- df %>%
    ggplot() +
    geom_sf(aes(fill = dkl_block), size = 0.001) +
    scale_fill_viridis_c(option = "magma", direction = -1, limits = c(0, max_range)) +
    labs(title = paste('DKL for', variable, year, ", Houston")) +
    theme_minimal() + 
    theme(legend.title = element_blank(), 
          legend.key.width = unit(0.5, "cm"),
          legend.key.height = unit(0.5, "cm"),
          legend.text = element_text(size = 7),
          axis.text = element_blank(),
          axis.title = element_blank())
  return(fig)
}
```

```{r}
max_range <- max(max(df_houst_race$dkl_block), max(df_houst_race$dkl_block))

r15 <- map_dkl(df_houst_race, "Race/Ethnicity", "2015", max_range)
r20 <- map_dkl(df_houst_race, "Race/Ethnicity", "2020", max_range)

r15 + r20
```



