---
title: "data_exploration"
author: "Ivanna Rodríguez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, arrow, sf, tidycensus, viridis, patchwork)

df15_dkl <- read_parquet("data/df15_dkl.parquet")
df20_dkl <- read_parquet("data/df20_dkl.parquet")
```

```{r, include=FALSE}
# get geographic data for maps
geom_tract_20 <- get_acs(year = 2020, geography = "tract", survey = 'acs5', variables = 'B02001_001', state = '17', county = '031', geometry = TRUE) %>%
  select(GEOID) %>% st_transform(crs = st_crs(4326)) 

geom_tract_15 <- get_acs(year = 2015, geography = "tract", survey = 'acs5', variables = 'B02001_001', state = '17', county = '031', geometry = TRUE) %>%
  select(GEOID) %>% st_transform(crs = st_crs(4326)) 

community_areas <- sf::st_read('https://data.cityofchicago.org/api/geospatial/cauq-8yn6?method=export&format=GeoJSON') %>% 
  st_transform(crs = st_crs(4326)) %>% 
  st_as_sf() %>% 
  select(community)

geom_tract_20 <- geom_tract_20 %>%
  st_join(., community_areas, left= TRUE, largest = TRUE) %>%
  filter(!is.na(community))

geom_tract_15 <- geom_tract_15 %>%
  st_join(., community_areas, left= TRUE, largest = TRUE) %>%
  filter(!is.na(community))
```

```{r}
# income buckets
all_dkl <- bind_rows(
  mutate(df15_dkl, year = 2015),
  mutate(df20_dkl, year = 2020)
)

buckets_all <- all_dkl

lvls <- all_dkl %>% 
  filter(group_label == 'Household income') %>% 
  select(label) %>% 
  distinct() %>% 
  pull(label)

buckets_all$label <- factor(buckets_all$label, levels = lvls)

buckets_all %>%
  filter(group_label == 'Household income', cbsa_fips == '16980') %>%
  select(group_label, cbsa_fips, label, dkl_bin, year) %>%
  distinct() %>%
  ggplot(aes(x = dkl_bin, y = label, fill = as.integer(label))) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(dkl_bin, digits=2)), hjust = -0.1, size = 3) +
  scale_fill_viridis_c() +
  facet_wrap(~year, scales = "free_y") +
  labs(title = "DKL by Income Buckets",
       subtitle = "For Chicago-Naperville-Elgin, IL-IN-WI") +
  theme_minimal() +
  theme(legend.position = "none",
        axis.title.y = element_blank())
```
```{r}
buckets_all %>%
  filter(group_label == 'Household income', cbsa_fips == '16980') %>%
  select(group_label, cbsa_fips, label, dkl_bin, year) %>%
  distinct() %>%
  ggplot(aes(x = label, y = dkl_bin, fill = factor(year))) +
  coord_flip() +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = round(dkl_bin, digits = 2)), position = position_dodge(width = 0.9), hjust = -0.1, size = 3) +
  scale_fill_manual(values = c("2015" = "blue", "2020" = "red")) +  # Set custom colors for each year
  theme_minimal() +
  theme(legend.position = "top")
```





```{r}
# race maps
p_rac_15 <- geom_tract_15 %>% 
  left_join(df15_dkl, by = c('GEOID'='tract_fips')) %>% 
  filter(group_label == 'Race') %>%
  ggplot(aes(fill = dkl_tract , color =  dkl_tract)) +
  geom_sf() + 
  scale_fill_viridis() + 
  scale_color_viridis() +
  labs(title = 'DKL for Race, 2015') +
  theme_minimal() + 
  theme(legend.title = element_blank(), 
        axis.text = element_blank())

p_rac_20 <- geom_tract_20 %>% 
  left_join(df20_dkl, by = c('GEOID'='tract_fips')) %>% 
  filter(group_label == 'Race') %>%
  ggplot(aes(fill = dkl_tract , color =  dkl_tract)) +
  geom_sf() + 
  scale_fill_viridis() + 
  scale_color_viridis() +
  labs(title = 'DKL for Race, 2020') +
  theme_minimal() + 
  theme(legend.title = element_blank(), 
        axis.text = element_blank())

p_rac_15 + p_rac_20
```



