---
title: "income maps"
author: "Ivanna Rodríguez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages(pacman)
pacman::p_load(sf, tigris, tidyverse, tidycensus, readxl, magrittr, here, arrow, patchwork)
```

```{r}
folder_10 <- 'E:/acs5_block_2010_data/'
folder_15 <- 'E:/acs5_block_2015_data/'
folder_20 <- 'E:/acs5_block_2020_data/'

plots_folder <- 'plots/'
```

```{r}
states <- c("IL", "NY", "TX", "GA")
cities <- c("Chicago", "New York", "Houston", "Atlanta")

get_fltr_data <- function(var) {
  df_10 <- read_parquet(paste0(folder_10, 
                             paste0("dkl_", var, "_10_blkgrp_all_states.parquet"))) %>%
  ungroup() %>%
  filter(state_codes %in% states,
         str_detect(cbsa_title, paste(cities, collapse = "|"))) %>%
    select(block_fips, county_fips, county_name, cbsa_fips, cbsa_title,
           state_codes, state_name, group_label, label, block_estimate, block_total,
           county_estimate, county_total, dkl_block, dkl_bin) %>%
    mutate(year = 2010)
  
  df_15 <- read_parquet(paste0(folder_15, 
                               paste0("dkl_", var, "_15_blkgrp_all_states.parquet"))) %>%
    ungroup() %>%
    filter(state_codes %in% states,
         str_detect(cbsa_title, paste(cities, collapse = "|"))) %>%
    select(block_fips, county_fips, county_name, cbsa_fips, cbsa_title,
           state_codes, state_name, group_label, label, block_estimate, block_total,
           county_estimate, county_total, dkl_block, dkl_bin) %>%
    mutate(year = 2015)
  
  df_20 <- read_parquet(paste0(folder_20, 
                               paste0("dkl_", var, "_20_blkgrp_all_states.parquet"))) %>%
    ungroup() %>%
    filter(state_codes %in% states,
         str_detect(cbsa_title, paste(cities, collapse = "|"))) %>%
    select(block_fips, county_fips, county_name, cbsa_fips, cbsa_title,
           state_codes, state_name, group_label, label, block_estimate, block_total,
           county_estimate, county_total, dkl_block, dkl_bin) %>%
    mutate(year = 2020)
  
  return(rbind(df_10, df_15, df_20))
}
```

```{r}
income <- get_fltr_data("income")
```

# Get Shapefiles

```{r}
state_codes <- income %>% 
  select(block_fips) %>% 
  mutate(state_code = str_sub(block_fips, 1, 2)) %>%
  select(state_code) %>%
  distinct() %>%
  pull(state_code)

counties <- income %>%
  select(county_fips, county_name, cbsa_title) %>%
  mutate(county_fips = str_sub(county_fips, 3, 5)) %>%
  distinct()

# map only the county in which each of the four cities is rather than cbsa ?
county_codes <- c('121', '031', '', '')
```


```{r}
get_block_shp <- function(state_code, county_codes) {
  get_acs(year = 2020, 
           geography = "block group", 
           survey = 'acs5', 
           variables = 'B19001_001', 
           state = state_code,
           county = county_codes,
           geometry = TRUE) %>%
    select(GEOID) %>% 
    st_transform(crs = st_crs(4326))
}
```

```{r}
atl_shp <- get_block_shp('13','121')
```
```{r}
nyc_shp <- get_block_shp('36', c('005', '081', '047', '061', '085'))
```
```{r}
chicago_shp <- get_block_shp('17', '031')
```

```{r}
houston_shp <- get_block_shp('48', '201')
```

```{r}
my_theme <- function() {
  theme_minimal() +
    theme(
      plot.title = element_text(size = 16, face = "bold"),
      plot.subtitle = element_text(size = 14),
      axis.title = element_text(size = 12, face = "bold"),
      axis.text = element_text(size = 10),
      legend.title = element_text(size = 10, face = "bold"),
      legend.text = element_text(size = 8),
    )
}
```



```{r}

map_dkl_block <- function(city, yr) {
  
  df <- income %>%
    filter(str_detect(cbsa_title, paste(city, collapse = "|")))
  
  max_range <- df %>%
    group_by(year) %>%
    summarise(max_dkl = max(dkl_block)) %>%
    pull(max_dkl) %>%
    max()
  
  df %<>% filter(year == yr)
  
  if (city == "Chicago") {
    shp <- chicago_shp
  }
  else if (city == "Houston") {
    shp <- houston_shp
  }
  else if (city == "Atlanta") {
    shp <- atl_shp
  }
  else if (city == "New York") {
    shp <- nyc_shp
  }
  
  shp %<>%
    left_join(df, by = c("GEOID" = "block_fips"))
  
  shp %>%
    ggplot() +
    geom_sf(aes(fill = dkl_block), size = 0.001) +
    scale_fill_viridis_c(option = "magma", direction = -1, limits = c(0, max_range)) +
    labs(title = city,
         subtitle = paste("DKL for Income in", yr),
         fill = "DKL (bits)") +  # Adding title to the legend
    my_theme() +
    theme(legend.key.width = unit(0.5, "cm"),
          legend.key.height = unit(0.5, "cm"),
          legend.text = element_text(size = 7),
          axis.text = element_blank(),
          axis.title = element_blank()) 
}

```


```{r}
atl_10 <- map_dkl_block("Atlanta", "2010")
atl_15 <- map_dkl_block("Atlanta", "2015")
atl_20 <- map_dkl_block("Atlanta", "2020")
```

```{r}
atl_10
ggsave(paste0(plots_folder, "map10_atl.png"), dpi = 300)

atl_15
ggsave(paste0(plots_folder, "map15_atl.png"), dpi = 300)

atl_20
ggsave(paste0(plots_folder, "map20_atl.png"), dpi = 300)
```
```{r}
nyc_10 <- map_dkl_block("New York", "2010")
nyc_15 <- map_dkl_block("New York", "2015")
nyc_20 <- map_dkl_block("New York", "2020")
```

```{r}
nyc_10
ggsave(paste0(plots_folder, "map10_nyc.png"), dpi = 300)

nyc_15
ggsave(paste0(plots_folder, "map15_nyc.png"), dpi = 300)

nyc_20
ggsave(paste0(plots_folder, "map20_nyc.png"), dpi = 300)
```

```{r}
hst_10 <- map_dkl_block("Houston", "2010")
hst_15 <- map_dkl_block("Houston", "2015")
hst_20 <- map_dkl_block("Houston", "2020")
```

```{r}
hst_10
ggsave(paste0(plots_folder, "map10_houston.png"), dpi = 300)

hst_15
ggsave(paste0(plots_folder, "map15_houston.png"), dpi = 300)

hst_20
ggsave(paste0(plots_folder, "map20_houston.png"), dpi = 300)
```

```{r}
chi_10 <- map_dkl_block("Chicago", "2010")
chi_15 <- map_dkl_block("Chicago", "2015")
chi_20 <- map_dkl_block("Chicago", "2020")
```

```{r}
chi_10
ggsave(paste0(plots_folder, "map10_chicago.png"), dpi = 300)

chi_15 
ggsave(paste0(plots_folder, "map15_chicago.png"), dpi = 300)

chi_20
ggsave(paste0(plots_folder, "map20_chicago.png"), dpi = 300)
```


